### train configuraton

save_path: exp/v1_ce_alignment_cosine_w1_english

train_list: data/v1_lists/English_train.txt
train_path: data/v1
mav_root: data/v1
mav_heard_list: English_test.txt
mav_unheard_list: Urdu_test.txt

max_epoch: 500
lr: 0.001
lr_decay: 0.97
augment: True
loss_type: ce

embedding_dim_a: 512
embedding_dim_v: 512

embedding_alignment: True
alignment_loss: cosine
alignment_weight: 1.0
