### train configuraton

save_path: exp/v1_share_ce_urdu

train_list: data/v1_lists/Urdu_train.txt
train_path: data/v1
mav_root: data/v1
mav_heard_list: Urdu_test.txt
mav_unheard_list: English_test.txt

max_epoch: 500
lr: 0.001
lr_decay: 0.97
augment: True
loss_type: ce

embedding_dim_a: 512
embedding_dim_v: 512
share_head: True
